import { useCallback, useEffect, useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import styles from "../../styles/Merchant/forgotpassword.module.scss";
import Cancel from "components/svg-icons/cancel";
import router from "next/router";

const OtpNumber: NextPage = () => {
  const [otp1, setOtp1] = useState("");
  const [otp2, setOtp2] = useState("");
  const [otp3, setOtp3] = useState("");
  const [otp4, setOtp4] = useState("");

  return (
    <div className="">
      <Head>
        <title>Merchant OnBoarding</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div>
        <div className={styles.loginmessage}>
          <span>OTP</span>
        </div>
        <div className={styles.otpmain}>
          <div>
            <input
              className={styles.otpbox}
              type="text"
              name="ss"
              onChange={(e) => setOtp1(e.target.value)}
              value={otp1}
              pattern={`\b([0-9]|1)\b`}
              maxLength={1}
            />
          </div>
          <div>
            <input
              className={styles.otpbox}
              type="tel"
              name="dd"
              onChange={(e) => setOtp2(e.target.value)}
              value={otp2}
              pattern={`\b([0-9]|1)\b`}
              maxLength={1}
            />
          </div>
          <div>
            <input
              className={styles.otpbox}
              type="text"
              name="fdf"
              onChange={(e) => setOtp3(e.target.value)}
              value={otp3}
              pattern={`\b([0-9]|1)\b`}
              maxLength={1}
            />
          </div>
          <div>
            <input
              className={styles.otpbox}
              type="tel"
              name="fff"
              onChange={(e) => setOtp4(e.target.value)}
              value={otp4}
              pattern={`\b([0-9]|1)\b`}
              maxLength={1}
            />
          </div>
        </div>
      </div>
    </div>
  );
};

export default OtpNumber;
